Angle testing
libretro/mupen64plus-libretro-nx pull request #342
Opened 2021-05-26 02:17 UTC by Nun-z

Does this meet your requirements?  I transferred the changes to the angle_testing branch.

2021-05-28 12:33 UTC, m4xw requested changes

2021-05-28 12:33 UTC, m4xw commented on libretro/libretro.c
> +#if defined(HAVE_ANGLE) && defined(__MINGW32__)
\n before #if

2021-05-28 12:34 UTC, m4xw requested changes

2021-05-28 12:34 UTC, m4xw commented on Makefile
> +ifeq ($(HAVE_ANGLE),1)
\n before ifeq

2021-05-29 05:03 UTC, Nun-z commented on mupen64plus-core/src/main/rom.c
> +
I'm not 100% on what you want here.  Is it something like what I just committed?

2021-06-05 09:49 UTC, Nun-z commented on libretro/libretro.c
> +#if defined(HAVE_ANGLE) && defined(__MINGW32__)
New line was added.

2021-06-05 09:49 UTC, Nun-z commented on Makefile
> +ifeq ($(HAVE_ANGLE),1)
New line was added.

2021-06-17 15:12 UTC, m4xw commented
I will get back at this PR when i wrap up the upcoming mupen core update

2021-07-14 13:54 UTC, m4xw commented
Looks fine for now. If i find some issue later, i will let you know.

2021-07-14 13:54 UTC, merged

2021-10-05 11:24 UTC, m4xw commented
@Nun-z can u check my angle branch (not angle-testing)?
https://cdn.discordapp.com/attachments/876520593636335646/894907594123132938/angle_mupen64plus_next_libretro.dll

2021-10-06 04:35 UTC, Nun-z commented
Sorry, something came up today, but I should have a chance to look at it
within 24 hours.

On Tue, Oct 5, 2021 at 4:24 AM m4xw ***@***.***> wrote:

> @Nun-z <https://github.com/Nun-z> can u check my angle branch (not
> angle-testing)?
>
> https://cdn.discordapp.com/attachments/876520593636335646/894907594123132938/angle_mupen64plus_next_libretro.dll
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/libretro/mupen64plus-libretro-nx/pull/342#issuecomment-934318678>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANBSS5BR5PHUULBXS5SCSPLUFLN7NANCNFSM45QTY5BA>
> .
>