Build on OSX
libretro/mupen64plus-libretro-nx pull request #474
Opened 2023-01-16 06:36 UTC by warmenhoven

This gets mupen64plus_next running on OSX, both on x64 and arm64.

2023-01-17 19:52 UTC, m4xw requested changes

2023-01-17 19:52 UTC, m4xw commented on mupen64plus-rsp-paraLLEl/jit_allocator.cpp
> +    size_t pagesize = sysconf(_SC_PAGESIZE) - 1;
sysconf isn't available on all systems, for libnx i provide it myself from inside RA.
Can't rely on that for the core tho

2023-01-18 04:35 UTC, warmenhoven commented
Something like this? https://github.com/Themaister/parallel-rsp/pull/5 (This is closer to what flycast does as well.)

2023-01-24 12:12 UTC, m4xw commented
I still need to do some local test, i think the ASSIGN_PROC_ADR change is sane to do on all platforms either way.
Other than that it looks acceptable, will get to it the next time i touch it (sometime this week)

2023-01-24 13:56 UTC, warmenhoven commented
Thanks! Yes, the `ASSIGN_PROC_ADR` change should be safe on all platforms. It could potentially mask problems, so I wasn't sure if it would be preferable to limit the cast to just Mac. I can change it so it applies to all platforms.

2023-01-24 17:05 UTC, warmenhoven commented
I've changed `ASSIGN_PROC_ADR` so it applies to all platforms instead of just osx, and I've rebased onto the current `develop` branch.

2023-01-24 17:33 UTC, m4xw commented
That reminds me, subrepo has a incorrect parent reference. Can u just squash out the parallel rsp change and i will just pull it on my end after merge?

2023-01-24 17:36 UTC, warmenhoven commented
Yep, I've removed the parallel-rsp change. The osx build might fail until the subrepo is pulled though as rsp_jit.cpp did have a cast fix.

2023-01-24 17:37 UTC, m4xw commented
I still see the mupen64plus-rsp-paraLLEl/jit_allocator.cpp change.
If its upstream then i dont need any change for the folder

2023-01-24 17:38 UTC, warmenhoven commented
Yep, sorry, missed that. Fixed now. Thanks!

2023-01-24 17:49 UTC, m4xw commented
Actually i forgot I dont have my own remote there.... subrepo was fine :P 
I'd prefer to not resolve that conflict in the future tho so will just force clone in the future but whatever for now

2023-01-24 17:49 UTC, merged

2023-01-24 18:04 UTC, m4xw commented
https://git.libretro.com/libretro/mupen64plus-libretro-nx/-/jobs/3068798 arm64 is faulty

2023-01-24 18:11 UTC, m4xw commented
did a short change, must be arch detection being faulty for apple cross comp